name: Deploy Keycloak with Custom Theme

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_SERVER_IP }}
          username: ${{ secrets.AZURE_SERVER_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          port: ${{ secrets.AZURE_SSH_PORT }}
          script: |
            set -e
            cd /home/azureuser/keycloack
            git fetch --all
            git reset --hard origin/main
            docker compose down || true
            docker compose pull
            docker compose up -d
