name: Deploy Keycloak with Custom Theme

on:

  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Keycloak image
        run: |
          docker build -t ${{ secrets.REGISTRY_SERVER }}/custom-keycloak:latest .
          docker push ${{ secrets.REGISTRY_SERVER }}/custom-keycloak:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_SERVER_IP }}
          username: ${{ secrets.AZURE_SERVER_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          port: ${{ secrets.AZURE_SSH_PORT }}
          script: |
            docker login ${{ secrets.REGISTRY_SERVER }} -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
            docker pull ${{ secrets.REGISTRY_SERVER }}/custom-keycloak:latest
            cd /home/azureuser/keycloak
            docker compose down || true
            docker compose up -d
